chore : 배포 중 발생한 도커 네트워크 관련 오류 수정
- 도커 이미지 기반으로 docker compose 명령어 실행 직전 도커 네트워크부터 먼저 탐색하도록 수정

diff --git a/.github/actions/deploy-vm/action.yaml b/.github/actions/deploy-vm/action.yaml
--- a/.github/actions/deploy-vm/action.yaml
+++ b/.github/actions/deploy-vm/action.yaml
@@ -102,6 +102,11 @@ runs:
             sudo mv /tmp/docker-compose.prod.yaml ${{ inputs.work_dir }}/docker-compose.prod.yaml
             sudo mv /tmp/promtail-config.yml ${{ inputs.work_dir }}/promtail-config.yml
             cd ${{ inputs.work_dir }}
+        
+            if ! sudo docker network inspect pgsg-network > /dev/null 2>&1; then
+              echo 'pgsg-network not found. Creating...'
+              sudo docker network create pgsg-network
+            fi
 
             sudo env IMAGE_TAG=\"${{ inputs.image_tag }}\" AR_IMAGE_PATH=\"${{ inputs.ar_image_path }}\" \
               docker compose -f docker-compose.prod.yaml pull
