fix : 배포 오류 수정
- 배포 성공 직후 에러가 발생하면서 강제종료되는 문제 수정

diff --git a/.github/actions/deploy-vm/action.yaml b/.github/actions/deploy-vm/action.yaml
--- a/.github/actions/deploy-vm/action.yaml
+++ b/.github/actions/deploy-vm/action.yaml
@@ -113,7 +113,10 @@ runs:
               sleep ${{ inputs.health_interval }}
             done
 
-            [ \"\$HEALTHY\" != '1' ] && echo 'Actuator health check failed.' && exit 1
+            if [ \"\$HEALTHY\" != '1' ]; then
+              echo 'Actuator health check failed.'
+              exit 1
+            fi
           "
 
     - name: Rollback
